#!/bin/sh

cwd=$(pwd)
name=$(basename "$cwd" | cut -d- -f 2-)
py=$(echo "$name" | cut -d- -f1)
venv=/home/buildbot/venv/$py
basedir=/home/buildbot/worker/$name

cd "$basedir"
exec chpst -u buildbot \
    env HOME=/home/buildbot \
    $venv/bin/buildbot-worker start --nodaemon
